### ISSUE TITLE
Better timestamp handling

### ISSUE THREAD

**Issue by fafrd** [crypt0biwan/curio-sales-bot#3]
We should use a less ambigious date format- YYYY-MM-DD is more clear imo, less ambigious between usa/european time formatting.

For the time, we should either mark this explicitly as UTC (i.e. 2:16 AM UTC) or use Discord's neat timezone-irrelelvant syntax. 

The following discord syntax will map to the client's timezone automatically: i.e. if you're in pacific time, `<t:123456789:f>` will map to "November 29, 1973 1:33 PM". This would be nice to have, but i'm not sure if we can keep the nice tiny text and use this?

discord timestamp syntax docs: https://c.r74n.com/discord/formatting#Timestamps

**Comment by crypt0biwan** [comment]
I think we just have to use the `timestamp` property for the embed msg https://discordjs.guide/popular-topics/embeds.html#using-an-embed-object

**Comment by fafrd** [comment]
Timestamp on the embed is a neat feature
